### PR TITLE
portfolio-project: Access-Ability

### PR DESCRIPTION
**Pull request by Moh9998**
Added Access Ability 💯 : 
-Added the `alt` Attribute
-edited some of the index.html to meet the requirements

### CODE REVIEW

**Review by Bondok6 — COMMENTED** [review]
## Hi @Moh9998 🙋‍♂️, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has been done individually and this is a pair programming project. Everyone on your team should make a commit in this PR.

image

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Moh9998** [comment]
I'm currently working alone so I don't know what to do

**Comment by Bondok6** [comment]
> I'm currently working alone so I don't know what to do

Hi @Moh9998, 
Do you mean you don't have a partner?

**Comment by Moh9998** [comment]
Yes

**Comment by Bondok6** [comment]
> Yes

Please, can you provide a screenshot of a message you have received from the student success in this regard?

**Comment by Moh9998** [comment]
I didn't resave any message but my partner never spoke to me at all

**Comment by Moh9998** [comment]
I received this email today I hope it helps

**Comment by Moh9998** [comment]
Oh ok thanks for your time 😊😊

**Review by awais-amjed — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED ♻️

Hi @Moh9998 , 

Good job so far! 👏👏
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- [x] Descriptive Pull Request ✔️
- [x] Nice Design ✔️
- [x] Good code organization ✔️ 

gif

## Required Changes ♻️

- [ ] Kindly update the title of page so that it adequately and briefly describes the content of the page 🤗 For example:
  - Poor titles:
    - Microverse project | Your portfolio.
    - Portifolio project
  - Better page titles:
    - Mark's portfolio
    - Mark full-stack web developer

- [ ] Kindly update the alt text of all your works images in such a way that it explains what the image is about. You can check more information on how to write better alt text [here](https://www.w3.org/WAI/test-evaluate/preliminary/#images)  🤗

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by awais-amjed — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED ♻️

Hi @Moh9998 , 

Great work on making the changes requested by a previous reviewer 👏👏👏
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Highlights

- [x] Descriptive Pull Request ✔️
- [x] Nice Design ✔️
- [x] Good code organization ✔️ 

gif

 ## Required Changes ♻️

- [ ] I believe you misunderstood me before 😅 kindly update the title on `line 7` (in the `head tag`) of your Project according to the details mentioned in the previous review, instead of the PR title. You can read more about writing a good title [here](https://www.w3.org/WAI/test-evaluate/preliminary/#title) 🤗

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by awais-amjed — APPROVED** [review]
# STATUS: APPROVED 🥳

Hi @Moh9998 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations on implementing all the required changes! 🎉👏🥇✨

## Highlights

- [x] Descriptive Pull Request ✔️
- [x] Nice Design ✔️
- [x] Good code organization ✔️ 

gif

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
