### PR TITLE
Protifolio project mobile version

### PR DESCRIPTION
**Pull request by Moh9998**
creating my very first mobile version of protifplio page

### CODE REVIEW

**Review by Ugboaja-Uchechi — COMMENTED** [review]
Hi @Moh9998 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have the necessary linters set up. Please make sure you set up all necessary linters before resubmitting 🙏 .

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Moh9998** [comment]
how do I set up my linters   I already added them to the project file??

**Review by Kandy-Peter — COMMENTED** [review]
# STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @Moh9998 
While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project that has some issues needed to be fixed before reviewing it:
- [x] You may be added all files but no one is running, Kindly make sure you follow all the steps to set up liners and everything is installed.  Please, follow the instructions given in this [README file](https://github.com/microverseinc/linters-config/tree/master/html-css) for more.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

---
Cheers and Happy coding!👏👏👏

---
_Invalid Code Review Request **Does not count** into the code reviews limit._

**Comment by Ugboaja-Uchechi** [comment]
> how do I set up my linters I already added them to the project file??

Hi @Moh9998 , you can reach out to me on slack @tired coder if you're still having issues setting up your linters

**Review by Ugboaja-Uchechi — APPROVED** [review]
Hi @Moh9998, 

## Status: APPROVED

Image

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- Linters are passing ✔️ 
- Your repo looks professional 👏 
- Great job with your design 👍 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Moh9998** [comment]
final commit for this pull request

**Pull request merged**
